In [44]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [45]:
df = pd.read_csv('homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [46]:
%matplotlib inline
plt.xlabel('Area (sqft)')
plt.ylabel('Price ($)')
plt.scatter(df.area,df.price,color = "red",marker='+')


In [47]:

# linear regression - y = mx + b # m = co-efficient , b = intercept

reg = linear_model.LinearRegression()
reg.fit(df[['area']],df.price) # first argument is input,second argument target variable (price) to be predicted.
#after fitting the model we can predict by input that is not in the dataset

LinearRegression()

In [48]:
reg.predict([[3300]])# if x = 3300 sqft then predicted price array([628715.75342466])

/Users/admin/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([628715.75342466])

In [49]:
reg.coef_ # m = coefficient

array([135.78767123])

In [50]:
reg.intercept_ # b = intercept 

180616.43835616432

In [24]:
# y = mx + b
# testing for x = 3300, what will be the price(y) ?
x = 3300
m = reg.coef_
b = reg.intercept_
y = m*x + b
print("Manually ", y)
print("Done with library ", reg.predict([[3300]]))
# we can see that the answer is same 


Manually  [628715.75342466]
Done with library  [628715.75342466]


/Users/admin/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [51]:
# y = mx + b
# testing for x = 5000, what will be the price(y) ?
x = 5000
m = reg.coef_
b = reg.intercept_
y = m*x + b
print("Manually ", y)
print("Done with library ", reg.predict([[5000]]))
# we can see that the answer is same 


Manually  [859554.79452055]
Done with library  [859554.79452055]


/Users/admin/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [52]:
# working with csv
df1 = pd.read_csv('areas.csv')
df1

area
0   1000
1   1500
2   2300
3   3540
4   4120
5   4560
6   5490
7   3460
8   4750
9   2300
10  9000
11  8600
12  7100

In [53]:
# now predicting price for the areas 

p = reg.predict(df1)
p

array([ 316404.10958904,  384297.94520548,  492928.08219178,
        661304.79452055,  740061.64383562,  799808.21917808,
        926090.75342466,  650441.78082192,  825607.87671233,
        492928.08219178, 1402705.47945205, 1348390.4109589 ,
       1144708.90410959])

In [54]:
df1['Predicted Price'] = p 
df1

area  Predicted Price
0   1000     3.164041e+05
1   1500     3.842979e+05
2   2300     4.929281e+05
3   3540     6.613048e+05
4   4120     7.400616e+05
5   4560     7.998082e+05
6   5490     9.260908e+05
7   3460     6.504418e+05
8   4750     8.256079e+05
9   2300     4.929281e+05
10  9000     1.402705e+06
11  8600     1.348390e+06
12  7100     1.144709e+06

In [36]:
# # to save the new df
# df.to_csv('Predicted.csv',index=False)

In [59]:
%matplotlib inline
plt.xlabel('Area (sqft)',fontsize = 20)
plt.ylabel('Price ($)',fontsize = 20)
plt.scatter(df.area,df.price,color = 'red',marker='+')
plt.plot(df1.area,p,color="blue") # second peramenter = p = predicted prices